# Generated by Django 4.2.6 on 2024-05-12 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Дополнительный водитель Каско',
                'verbose_name_plural': 'Дополнительные водители Каско',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название марки')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('horsepower', models.IntegerField(verbose_name='Лошадиные силы')),
                ('model_name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная стоимость')),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимальная стоимость')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casco.brand', verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
            },
        ),
        migrations.CreateModel(
            name='CascoClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обращения')),
                ('description', models.TextField(verbose_name='Описание случая')),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма выплаты')),
                ('processed', models.BooleanField(default=False, verbose_name='Проработана')),
                ('availability_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.appraiserschedule', verbose_name='Расписание Оценщика')),
                ('insurance_appraiser_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Страховой оценщик')),
            ],
            options={
                'verbose_name': 'Обращение КАСКО',
                'verbose_name_plural': 'Обращения КАСКО',
            },
        ),
        migrations.CreateModel(
            name='CascoPayoutAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_character', models.TextField(verbose_name='Характер повреждения')),
                ('percentage_of_insurance_amount', models.FloatField(verbose_name='Процент от страховой суммы')),
            ],
            options={
                'verbose_name': 'Оценка выплаты Каско',
                'verbose_name_plural': 'Оценки выплат Каско',
            },
        ),
        migrations.CreateModel(
            name='CascoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_drivers', models.IntegerField(verbose_name='Количество лиц, допущенных к управлению')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
                ('coverage', models.CharField(choices=[('full', 'Полное покрытие'), ('theft_destruction', 'Угон + гибель авто'), ('damage_destruction', 'Ущерб + гибель авто')], max_length=20, verbose_name='Покрытие')),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость страховки')),
                ('processed', models.BooleanField(default=False, verbose_name='Проработана')),
                ('repair_type', models.CharField(choices=[('dealer', 'Дилерский центр'), ('specialized_service', 'Специализированный сервис'), ('express_repair', 'Экспресс-ремонт')], max_length=255, verbose_name='Тип ремонта')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('cost_guarantee', models.BooleanField(default=False, verbose_name='Гарантия стоимости')),
                ('car_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость авто')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casco.carmodel', verbose_name='Модель автомобиля')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.agentschedule', verbose_name='Расписание агента')),
            ],
            options={
                'verbose_name': 'Запись на прием Каско',
                'verbose_name_plural': 'Записи на прием Каско',
            },
        ),
        migrations.CreateModel(
            name='DriversCascoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casco_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casco.cascorecord', verbose_name='Запись Каско')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casco.additionaldriver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Запись водителя Каско',
                'verbose_name_plural': 'Записи водителей Каско',
            },
        ),
        migrations.CreateModel(
            name='CascoContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заключения')),
                ('start_date', models.DateField(verbose_name='Начало действия договора')),
                ('end_date', models.DateField(verbose_name='Конец действия договора')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casco.driverscascorecord', verbose_name='Агент')),
                ('casco_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casco.cascorecord', verbose_name='Запись Каско')),
            ],
            options={
                'verbose_name': 'Договор Каско',
                'verbose_name_plural': 'Договора Каско',
            },
        ),
        migrations.CreateModel(
            name='CascoClaimAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casco_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casco.cascoclaim', verbose_name='Обращение КАСКО')),
                ('payout_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casco.cascopayoutassessment', verbose_name='Оценка КАСКО')),
            ],
            options={
                'verbose_name': 'Связь Обращение - Оценка КАСКО',
                'verbose_name_plural': 'Связи Обращение - Оценка КАСКО',
            },
        ),
        migrations.AddField(
            model_name='cascoclaim',
            name='insurance_contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casco.cascocontract', verbose_name='Договор КАСКО'),
        ),
    ]
