# Generated by Django 4.2.6 on 2024-05-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casco', '0003_remove_cascorecord_processed_cascorecord_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascorecord',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='pending', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
