# Generated by Django 4.2.6 on 2024-05-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casco', '0005_remove_cascorecord_number_of_drivers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cascorecord',
            name='driver_restriction',
        ),
    ]
