# Generated by Django 4.2.6 on 2024-05-15 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casco', '0006_remove_cascorecord_driver_restriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverscascorecord',
            name='casco_record',
        ),
        migrations.RemoveField(
            model_name='driverscascorecord',
            name='driver_id',
        ),
        migrations.AlterField(
            model_name='cascocontract',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Агент'),
        ),
        migrations.DeleteModel(
            name='AdditionalDriver',
        ),
        migrations.DeleteModel(
            name='DriversCascoRecord',
        ),
    ]
