# Generated by Django 4.2.6 on 2024-05-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casco', '0008_remove_cascoclaim_processed_cascoclaim_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cascoclaim',
            name='insurance_appraiser_id',
        ),
    ]
