# Generated by Django 4.2.6 on 2024-05-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casco', '0010_remove_carmodel_coefficient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='price_min',
        ),
    ]
