# Generated by Django 4.2.6 on 2024-05-17 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casco', '0011_remove_carmodel_price_max_remove_carmodel_price_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тематики')),
            ],
            options={
                'verbose_name': 'Тема повреждения КАСКО',
                'verbose_name_plural': 'Темы повреждений КАСКО',
            },
        ),
        migrations.AddField(
            model_name='cascopayoutassessment',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casco.damagetheme', verbose_name='Тематика повреждения'),
        ),
    ]
