# Generated by Django 4.2.6 on 2024-05-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casco', '0012_damagetheme_cascopayoutassessment_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascopayoutassessment',
            name='damage_character',
            field=models.TextField(unique=True, verbose_name='Характер повреждения'),
        ),
    ]
