# Generated by Django 4.2.6 on 2024-02-20 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentshealth',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_health', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='appointmentscar',
            name='available',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.availability', verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='appointmentscar',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_car', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
