# Generated by Django 4.2.6 on 2024-02-20 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTableHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_damage', models.CharField(max_length=255, verbose_name='Характер повреждения')),
                ('percent', models.IntegerField(verbose_name='Процент от страх. суммы')),
            ],
        ),
        migrations.CreateModel(
            name='ContractHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signing', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_health_agent', to=settings.AUTH_USER_MODEL, verbose_name='Страховой агент')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.appointmentshealth', verbose_name='Запись')),
            ],
        ),
    ]
