# Generated by Django 4.2.6 on 2024-02-20 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0005_alter_appointmentshealth_sum_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signing', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_car_agent', to=settings.AUTH_USER_MODEL, verbose_name='Страховой агент')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.appointmentscar', verbose_name='Запись')),
            ],
        ),
    ]
