# Generated by Django 4.2.6 on 2024-02-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_contractcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTableCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_damage_car', models.CharField(max_length=255, verbose_name='Характер повреждения')),
                ('percent_car', models.IntegerField(verbose_name='Процент от страх. суммы')),
            ],
        ),
    ]
