# Generated by Django 4.2.6 on 2024-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_paymenttablecar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentshealth',
            name='age_coefficient',
            field=models.FloatField(choices=[(1, 'От 3 до 17 лет'), (1.5, 'От 18 до 35 лет'), (1.8, 'От 36 до 65 лет')], max_length=100, verbose_name='Возрастной коэффициент'),
        ),
        migrations.AlterField(
            model_name='appointmentshealth',
            name='duration',
            field=models.FloatField(choices=[(1, '1 год'), (1.2, '6 месяцев'), (1.3, '3 месяца'), (1.5, '1 месяц')], max_length=100, verbose_name='Длительность страхования'),
        ),
        migrations.AlterField(
            model_name='appointmentshealth',
            name='sport_coverage',
            field=models.FloatField(choices=[(1.2, 'Обычный'), (1.4, 'Расширенный')], max_length=100, verbose_name='Категория спортивного покрытия'),
        ),
        migrations.AlterField(
            model_name='appointmentshealth',
            name='sum_insurance',
            field=models.FloatField(choices=[(1.1, '100.000'), (1.3, '250.000'), (1.5, '500.000')], max_length=100, verbose_name='Сумма страхования'),
        ),
    ]
