# Generated by Django 4.2.6 on 2024-02-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_appointmentscar_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentshealth',
            name='is_active',
            field=models.BooleanField(default=False, null=True, verbose_name='Проработана'),
        ),
    ]
