# Generated by Django 4.2.6 on 2024-02-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_appointmentshealth_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentshealth',
            name='additional_sports',
            field=models.CharField(default=False, max_length=100, null=True, verbose_name='Дополнительные виды спорта'),
        ),
        migrations.AlterField(
            model_name='appointmentshealth',
            name='participation_in_competition',
            field=models.BooleanField(default=False, null=True, verbose_name='Участие в соревнованиях'),
        ),
    ]
