# Generated by Django 4.2.6 on 2024-05-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_agentschedule_options_and_more'),
        ('life', '0003_remove_lifeinsurancerecord_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeinsurancerecord',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.agentschedule', verbose_name='Доступность'),
        ),
    ]
