# Generated by Django 4.2.6 on 2024-05-14 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentschedule',
            options={'verbose_name': 'Расписание агента', 'verbose_name_plural': 'Расписание агентов'},
        ),
        migrations.AlterModelOptions(
            name='appraiserschedule',
            options={'verbose_name': 'Расписание Оценщика', 'verbose_name_plural': 'Расписание Оценщиков'},
        ),
        migrations.AlterField(
            model_name='appraiserschedule',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценщик'),
        ),
    ]
