# Generated by Django 4.2.6 on 2024-05-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osago', '0002_alter_osagorecord_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osagorecord',
            name='processed',
        ),
        migrations.AddField(
            model_name='osagorecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
