# Generated by Django 4.2.6 on 2024-05-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osago', '0003_remove_osagorecord_processed_osagorecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osagorecord',
            name='number_of_drivers',
        ),
        migrations.DeleteModel(
            name='DriversOsagoRecord',
        ),
        migrations.DeleteModel(
            name='OsagoAdditionalDriver',
        ),
    ]
