# Generated by Django 4.2.6 on 2024-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osago', '0004_remove_osagorecord_number_of_drivers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osagoclaim',
            name='processed',
        ),
        migrations.AddField(
            model_name='osagoclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
