# Generated by Django 4.2.6 on 2024-05-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osago', '0005_remove_osagoclaim_processed_osagoclaim_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osagoclaim',
            name='appraiser',
        ),
    ]
