# Generated by Django 4.2.6 on 2024-05-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osago', '0006_remove_osagoclaim_appraiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageThemeOsagoAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тематики')),
            ],
            options={
                'verbose_name': 'Тема повреждения ОСАГО АВТО',
                'verbose_name_plural': 'Темы повреждений ОСАГО АВТО',
            },
        ),
        migrations.CreateModel(
            name='DamageThemeOsagoLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тематики')),
            ],
            options={
                'verbose_name': 'Тема повреждения ОСАГО Жизнь',
                'verbose_name_plural': 'Темы повреждений ОСАГО Жизнь',
            },
        ),
        migrations.AddField(
            model_name='osagoautopayoutassessment',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osago.damagethemeosagoauto', verbose_name='Тематика повреждения'),
        ),
        migrations.AddField(
            model_name='osagolifepayoutassessment',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osago.damagethemeosagolife', verbose_name='Тематика повреждения'),
        ),
    ]
