# Generated by Django 4.2.6 on 2024-05-12 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePayoutAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_character', models.TextField(verbose_name='Характер повреждения')),
                ('percentage_of_insurance_amount', models.FloatField(verbose_name='Процент от страховой суммы')),
            ],
            options={
                'verbose_name': 'Оценка выплаты по страхованию квартиры',
                'verbose_name_plural': 'Оценки выплат по страхованию квартиры',
            },
        ),
        migrations.CreateModel(
            name='HomeInsuranceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('apartment', models.CharField(max_length=10, verbose_name='Квартира')),
                ('interior_finish', models.IntegerField(verbose_name='Внутренняя отделка')),
                ('structural_elements', models.IntegerField(verbose_name='Конструктивные элементы')),
                ('civil_liability', models.IntegerField(verbose_name='Гражданская ответственность')),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость страховки')),
                ('processed', models.BooleanField(default=False, verbose_name='Проработана')),
                ('household_property', models.IntegerField(verbose_name='Домашнее имущество')),
                ('additional_protection', models.BooleanField(default=False, verbose_name='Дополнительная защита')),
                ('war_risk', models.BooleanField(blank=True, null=True, verbose_name='Риск военных действий')),
                ('neighbor_repair_liability', models.BooleanField(blank=True, null=True, verbose_name='Ответственность перед соседями при ремонте')),
                ('atmospheric_impact', models.BooleanField(blank=True, null=True, verbose_name='Воздействие атмосферных осадков')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.agentschedule', verbose_name='Расписание агента')),
            ],
            options={
                'verbose_name': 'Запись на прием по страхованию квартиры',
                'verbose_name_plural': 'Записи на прием по страхованию квартиры',
            },
        ),
        migrations.CreateModel(
            name='HomeInsuranceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заключения')),
                ('start_date', models.DateField(verbose_name='Начало действия')),
                ('end_date', models.DateField(verbose_name='Конец действия')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Агент')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.homeinsurancerecord', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Договор страхования квартиры',
                'verbose_name_plural': 'Договоры страхования квартир',
            },
        ),
        migrations.CreateModel(
            name='HomeInsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обращения')),
                ('description', models.TextField(verbose_name='Описание случая')),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма выплаты')),
                ('processed', models.BooleanField(default=False, verbose_name='Проработана')),
                ('appraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Страховой оценщик')),
                ('availability_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.appraiserschedule', verbose_name='Расписание Оценщика')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.homeinsurancecontract', verbose_name='Договор страхования квартиры')),
            ],
            options={
                'verbose_name': 'Обращение по страховому случаю квартиры',
                'verbose_name_plural': 'Обращения по страховым случаям квартир',
            },
        ),
        migrations.CreateModel(
            name='HomeClaimAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.homepayoutassessment', verbose_name='Оценка квартиры')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.homeinsuranceclaim', verbose_name='Обращение по страхованию квартиры')),
            ],
            options={
                'verbose_name': 'Связь Обращения и Оценки по страхованию квартиры',
                'verbose_name_plural': 'Связи Обращений и Оценок по страхованию квартир',
            },
        ),
    ]
