# Generated by Django 4.2.6 on 2024-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepayoutassessment',
            name='damage_character',
            field=models.TextField(unique=True, verbose_name='Характер повреждения'),
        ),
    ]
