# Generated by Django 4.2.6 on 2024-05-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_agentschedule_options_and_more'),
        ('property', '0002_alter_homepayoutassessment_damage_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeinsurancerecord',
            name='processed',
        ),
        migrations.AddField(
            model_name='homeinsurancerecord',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='pending', max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='homeinsurancerecord',
            name='civil_liability',
            field=models.PositiveIntegerField(choices=[(500000, '500 000 руб'), (1000000, '1 000 000 руб'), (1500000, '1 500 000 руб'), (2000000, '2 000 000 руб')], verbose_name='Гражданская ответственность'),
        ),
        migrations.AlterField(
            model_name='homeinsurancerecord',
            name='household_property',
            field=models.PositiveIntegerField(choices=[(500000, '500 000 руб'), (1000000, '1 000 000 руб'), (1500000, '1 500 000 руб'), (2000000, '2 000 000 руб')], verbose_name='Домашнее имущество'),
        ),
        migrations.AlterField(
            model_name='homeinsurancerecord',
            name='interior_finish',
            field=models.PositiveIntegerField(choices=[(500000, '500 000 руб'), (1000000, '1 000 000 руб'), (1500000, '1 500 000 руб'), (2000000, '2 000 000 руб')], verbose_name='Внутренняя отделка'),
        ),
        migrations.AlterField(
            model_name='homeinsurancerecord',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.agentschedule', verbose_name='Расписание агента'),
        ),
        migrations.AlterField(
            model_name='homeinsurancerecord',
            name='structural_elements',
            field=models.PositiveIntegerField(choices=[(500000, '500 000 руб'), (1000000, '1 000 000 руб'), (1500000, '1 500 000 руб'), (2000000, '2 000 000 руб')], verbose_name='Конструктивные элементы'),
        ),
    ]
