# Generated by Django 4.2.6 on 2024-05-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_homeinsurancerecord_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinsurancerecord',
            name='atmospheric_impact',
            field=models.BooleanField(default=False, verbose_name='Воздействие атмосферных осадков'),
        ),
        migrations.AlterField(
            model_name='homeinsurancerecord',
            name='neighbor_repair_liability',
            field=models.BooleanField(default=False, verbose_name='Ответственность перед соседями при ремонте'),
        ),
        migrations.AlterField(
            model_name='homeinsurancerecord',
            name='war_risk',
            field=models.BooleanField(default=False, verbose_name='Риск военных действий'),
        ),
    ]
