# Generated by Django 4.2.6 on 2024-05-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_homeinsuranceclaim_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageThemeHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тематики')),
            ],
            options={
                'verbose_name': 'Тема повреждения Квартира',
                'verbose_name_plural': 'Темы повреждений Квартира',
            },
        ),
        migrations.AddField(
            model_name='homepayoutassessment',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.damagethemehome', verbose_name='Тематика повреждения'),
        ),
    ]
